In [1]:
pip install pandas

Requirement already satisfied: pandas in .\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in .\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
a=[10,20,30,40,50]
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
b=[23.4,78.6,65.4,19.2,78.9]
pd.Series(b)

0    23.4
1    78.6
2    65.4
3    19.2
4    78.9
dtype: float64

In [5]:
c=["Python","java","c++","c","django"]
pd.Series(c)

0    Python
1      java
2       c++
3         c
4    django
dtype: str

In [6]:
d=[8+9j,5j,7j+8,3j+10,4j+6]
pd.Series(d)

0     8.0+ 9.0j
1     0.0+ 5.0j
2     8.0+ 7.0j
3    10.0+ 3.0j
4     6.0+ 4.0j
dtype: complex128

In [7]:
e=[True,False]
pd.Series(e)

0     True
1    False
dtype: bool

In [8]:
d={"names":["kavya","divya","vaishnavi"],"marks":[70,80,90]}
pd.DataFrame(d)

       names  marks
0      kavya     70
1      divya     80
2  vaishnavi     90

In [9]:
d={"Names":["kumar","girija","bharath"],"marks":[100,98,89],"grades":['A','B','C']}
pd.DataFrame(d)

     Names  marks grades
0    kumar    100      A
1   girija     98      B
2  bharath     89      C

In [10]:
d={"Names":["divya","kavya","vaishnavi","kumar","girija"],"Subjects":["social","Telugu","hindi","english","science"],"marks":[90,80,70,98,100]}
pd.DataFrame(d)

       Names Subjects  marks
0      divya   social     90
1      kavya   Telugu     80
2  vaishnavi    hindi     70
3      kumar  english     98
4     girija  science    100

In [11]:
d=pd.read_csv("Book1.csv")
d

        name  marks    subject
0      divya     90     social
1      sajad     93      hindi
2    adraysh     87    english
3    adrayth     80     telugu
4      varna     78   sanskrit
5      kumar     75      maths
6     girija     65    physics
7  vaishnavi     60  chemistry
8      kavya     92    biology

In [13]:
d.columns

Index(['name', 'marks', 'subject'], dtype='str')

In [14]:
d.shape

(9, 3)

In [15]:
d.info

<bound method DataFrame.info of         name  marks    subject
0      divya     90     social
1      sajad     93      hindi
2    adraysh     87    english
3    adrayth     80     telugu
4      varna     78   sanskrit
5      kumar     75      maths
6     girija     65    physics
7  vaishnavi     60  chemistry
8      kavya     92    biology>

In [16]:
data=pd.read_csv("cumulative.csv")
data

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,9560,10031643,K07984.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,0,...,-152.0,4.296,0.231,-0.189,1.088,0.313,-0.228,298.74921,46.973351,14.478
9560,9561,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,1,...,-166.0,4.529,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082
9561,9562,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,0,0,0,...,-220.0,4.444,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757
9562,9563,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0,0,1,...,-236.0,4.447,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385
9563,9564,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,1,...,-225.0,4.385,0.054,-0.216,1.193,0.410,-0.137,297.00977,47.121021,14.826

In [17]:
data.columns

Index(['rowid', 'kepid', 'kepoi_name', 'kepler_name', 'koi_disposition',
       'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_teq_err1', 'koi_teq_err2', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2',
       'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad',
       'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='str')

In [19]:
data.shape

(9564, 50)

In [20]:
data.info

<bound method DataFrame.info of       rowid     kepid kepoi_name   kepler_name koi_disposition  \
0         1  10797460  K00752.01  Kepler-227 b       CONFIRMED
1         2  10797460  K00752.02  Kepler-227 c       CONFIRMED
2         3  10811496  K00753.01           NaN  FALSE POSITIVE
3         4  10848459  K00754.01           NaN  FALSE POSITIVE
4         5  10854555  K00755.01  Kepler-664 b       CONFIRMED
...     ...       ...        ...           ...             ...
9559   9560  10031643  K07984.01           NaN  FALSE POSITIVE
9560   9561  10090151  K07985.01           NaN  FALSE POSITIVE
9561   9562  10128825  K07986.01           NaN       CANDIDATE
9562   9563  10147276  K07987.01           NaN  FALSE POSITIVE
9563   9564  10156110  K07989.01           NaN  FALSE POSITIVE

     koi_pdisposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0           CANDIDATE      1.000              0              0              0
1           CANDIDATE      0.969              0              0              0
2      FALSE POSITIVE      0.000              0              1              0
3      FALSE POSITIVE      0.000              0              1              0
4           CANDIDATE      1.000              0              0              0
...               ...        ...            ...            ...            ...
9559   FALSE POSITIVE      0.000              0              0              0
9560   FALSE POSITIVE      0.000              0              1              1
9561        CANDIDATE      0.497              0              0              0
9562   FALSE POSITIVE      0.021              0              0              1
9563   FALSE POSITIVE      0.000              0              0              1

      ...  koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  \
0     ...           -81.0      4.467           0.064          -0.096
1     ...           -81.0      4.467           0.064          -0.096
2     ...          -176.0      4.544           0.044          -0.176
3     ...          -174.0      4.564           0.053          -0.168
4     ...          -211.0      4.438           0.070          -0.210
...   ...             ...        ...             ...             ...
9559  ...          -152.0      4.296           0.231          -0.189
9560  ...          -166.0      4.529           0.035          -0.196
9561  ...          -220.0      4.444           0.056          -0.224
9562  ...          -236.0      4.447           0.056          -0.224
9563  ...          -225.0      4.385           0.054          -0.216

      koi_srad  koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag
0        0.927          0.105         -0.061  291.93423  48.141651      15.347
1        0.927          0.105         -0.061  291.93423  48.141651      15.347
2        0.868          0.233         -0.078  297.00482  48.134129      15.436
3        0.791          0.201         -0.067  285.53461  48.285210      15.597
4        1.046          0.334         -0.133  288.75488  48.226200      15.509
...        ...            ...            ...        ...        ...         ...
9559     1.088          0.313         -0.228  298.74921  46.973351      14.478
9560     0.903          0.237         -0.079  297.18875  47.093819      14.082
9561     1.031          0.341         -0.114  286.50937  47.163219      14.757
9562     1.041          0.341         -0.114  294.16489  47.176281      15.385
9563     1.193          0.410         -0.137  297.00977  47.121021      14.826

[9564 rows x 50 columns]>